### ISSUE TITLE
plan milestones

### ISSUE THREAD

**Issue by rcrath** [digiah/mjuke#4]
plan next few milestones to get this to alpha, beta, 1.0 and beyond.

**Comment by damg70** [comment]
1. Basic code review and addition of rights, credits, etc. at top of each file as appropriate... remove curse words from debug messages. **Target:BlueSky**
2. Test with multiple simultaneous users and simplified media library, document bugs and determine how severe they are. I don't think the bugs as they are (which are largely caused if there are communications lags on the network) will prevent us from getting to an alpha release status. 
3. Plan an actual UH event where users other than myself demonstrate the tool live. 

THese are taken up in https://github.com/digiah/2do/issues/150 and https://github.com/digiah/2do/issues/151 and https://github.com/digiah/2do/issues/152
